### ISSUE TITLE
pagination is broken if pagination container is placed outside of main container

### ISSUE THREAD

**Issue by algbeta** [denhartog/jquery-simple-pagination#1]
Hello guys,
The problem I'm describing is not a bug but an enhancement. The thing is according to your logic pagination buttons(next, previous, numbers etc) have to be placed in the main container otherwise the logic is broken  and that's not very suitable for many cases. 
I think it's quite easy to change/fix.
Thanks for your work!

**Comment by denhartog** [comment]
@algbeta,

Thanks for your evaluation. Can you please provide a more explicit example of your desired use case so that I may decide how to proceed? I am pretty sure you can achieve whatever you are imagining with simple-pagination just the way it is, and if that is the case, I would love to work with you to accomplish your goal.

Thanks!

**Comment by denhartog** [comment]
Due to a lack of response this issue has been closed. The desired functionality can be achieved by simply moving the container id/class to a parent further up the DOM to include the relevant children DOM.
